import React from 'react';
import Simulator from './components/Simulator';
import ScriptViewer from './components/ScriptViewer';
import { Tv, FolderGit2, Code2, MonitorPlay } from 'lucide-react';

const App: React.FC = () => {
  return (
    <div className="min-h-screen bg-slate-950 text-slate-200 font-sans selection:bg-emerald-500/30">
      
      {/* Hero Section */}
      <header className="border-b border-slate-800 bg-slate-900/50 backdrop-blur-sm sticky top-0 z-50">
        <div className="max-w-6xl mx-auto px-4 py-4 flex items-center justify-between">
          <div className="flex items-center space-x-3">
            <div className="bg-emerald-600 p-2 rounded-lg shadow-lg shadow-emerald-900/20">
              <Tv size={24} className="text-white" />
            </div>
            <div>
              <h1 className="text-xl font-bold text-white tracking-tight">JellySort</h1>
              <p className="text-xs text-slate-400">Windows 11 Series Organizer</p>
            </div>
          </div>
          <div className="flex items-center space-x-4 text-sm font-medium">
             <a href="#simulator" className="hover:text-emerald-400 transition-colors">Simulator</a>
             <a href="#download" className="hover:text-emerald-400 transition-colors">Get Script</a>
          </div>
        </div>
      </header>

      <main className="max-w-6xl mx-auto px-4 py-12 space-y-20">
        
        {/* Intro */}
        <section className="text-center space-y-6 max-w-3xl mx-auto">
          <h2 className="text-4xl md:text-5xl font-extrabold text-white leading-tight">
            Organize your library <br/>
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-emerald-400 to-cyan-400">
              with a smart GUI.
            </span>
          </h2>
          <p className="text-lg text-slate-400">
            A native <b>Windows GUI</b> Python tool. It features <b>Subtitle Support</b>, <b>Undo/Restore</b> via Manifest files, and automatic conflict handling. Rename your TV Series and Movies for Jellyfin/Plex compliance safely.
          </p>
        </section>

        {/* Simulator */}
        <section id="simulator" className="space-y-6">
          <div className="flex items-center justify-center space-x-2 mb-8">
            <FolderGit2 className="text-emerald-500" />
            <h3 className="text-2xl font-bold text-white">Logic Simulator</h3>
          </div>
          <p className="text-center text-slate-400 mb-8 max-w-2xl mx-auto">
            Test the sorting logic below. The simulator previews how video files are handled.
            <br/>
            <span className="text-xs text-emerald-400">* Note: The actual script also supports Subtitles (.srt) and Undo operations.</span>
          </p>
          <Simulator />
        </section>

        {/* Code Download */}
        <section id="download" className="pt-10 border-t border-slate-800">
          <div className="flex flex-col items-center justify-center space-y-4 mb-8">
            <div className="flex items-center space-x-2">
              <Code2 className="text-emerald-500" />
              <h3 className="text-2xl font-bold text-white">The GUI Script</h3>
            </div>
            <div className="text-center text-slate-400 max-w-2xl bg-slate-900 p-6 rounded-xl border border-slate-800">
              <div className="flex items-start justify-center space-x-4">
                 <MonitorPlay className="text-emerald-400 mt-1 shrink-0" size={24} />
                 <div className="text-left space-y-2">
                    <p className="text-white font-semibold">Native Windows Interface</p>
                    <p className="text-sm">This script launches a real graphical window on your PC. No command line required.</p>
                    <ul className="text-sm list-disc pl-4 space-y-1 text-slate-500">
                        <li><b>Manifest/Undo:</b> Automatically saves a JSON backup to revert changes.</li>
                        <li><b>Subtitles:</b> Moves .srt/.sub files alongside videos.</li>
                        <li><b>Safe:</b> Use "Dry Run" to test before applying.</li>
                    </ul>
                 </div>
              </div>
            </div>
          </div>
          <ScriptViewer />
        </section>

      </main>

      <footer className="bg-slate-900 border-t border-slate-800 py-8 mt-20">
        <div className="max-w-6xl mx-auto px-4 text-center text-slate-500 text-sm">
          <p>Generated by Google Gemini • Compatible with Windows 11 (Python 3.x)</p>
        </div>
      </footer>
    </div>
  );
};

export default App;